### ISSUE TITLE
Parrot

### ISSUE THREAD

**Issue by Baluna24** [ShaYmez/hblink3-docker-install#1]
Hello, how can I install the Parrot? Please give a short guide. Thanks very much

**Comment by k7ilo** [comment]
Any updates??

**Comment by ShaYmez** [comment]
HeyI’ll be updating docker to include a parrot config over the weekend, plus some container upgrades and re-images.If you can test that would be great,  feedback welcome.Shane M0VUB On 3 Aug 2023, at 00:47, k7ilo ***@***.***> wrote:﻿
Any updates??

**Comment by Baluna24** [comment]
Is the update already finished?

**Comment by Baluna24** [comment]
Is the update already finished?

**Comment by ShaYmez** [comment]
I will be adding parrot to the installer today :)SDOn 6 Aug 2023, at 10:30, Christian ***@***.***> wrote:﻿
Is the update already finished?

**Comment by ShaYmez** [comment]
Parrot now implemented in this install. The git repositiry for the source has also been updated for support of the parrot with docker-compose. Use ```- 'PARROT_ENABLE=1'``` in the updated docker compose YAML. Ive added new config too including example rules (Disabled by default). Enable these options. Ive included instructions on the README.md of this repo. The installer includes all the neccessary components for parrot and has been tested. Default TGID group call 9999, returns 9999 private call of playback.

Enjoy!

**Comment by ShaYmez** [comment]
Im now closing this as "Resolved" :) enjoy stable HBlink3!

**Comment by Baluna24** [comment]
after installation, the dashboard no longer works properly! It shows Connection closed. After the configuration and a new subscriber file, the same picture.

**Comment by ShaYmez** [comment]
Go to ..cd /opt/HBMonv2 run python3 monitor.py Send me the the log output off the screen Shane M0VUB Sent from my iPhoneOn 10 Aug 2023, at 21:07, Christian ***@***.***> wrote:﻿
after installation, the dashboard no longer works properly! It shows Connection closed. After the configuration and a new subscriber file, the same picture.

**Comment by Baluna24** [comment]
2023-08-11 13:16:05,807 INFO ID ALIAS MAPPER: 'peer_ids.json' is current, not downloaded
2023-08-11 13:16:05,808 INFO ID ALIAS MAPPER: 'subscriber_ids.json' is current, not downloaded
Traceback (most recent call last):
  File "/opt/HBMonv2/monitor.py", line 996, in <module>
    peer_ids = mk_full_id_dict(PATH, PEER_FILE, 'peer')
  File "/opt/HBMonv2/monitor.py", line 130, in mk_full_id_dict
    records = jload(_handle)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ShaYmez** [comment]
delete everything in /opt/HBMonv2/data/ all the json… it seems that when it downloaded the JSON it didn’t download it properly hence the error. Delete everything in that folder and restart by executing monitor.py. Once the dashbiard starts and is communicating properly, Cntrl C out and bring it back up using “systemctl restart hbmon”Thanks M0VUBSent from my iPhoneOn 11 Aug 2023, at 14:17, Christian ***@***.***> wrote:﻿
2023-08-11 13:16:05,807 INFO ID ALIAS MAPPER: 'peer_ids.json' is current, not downloaded
2023-08-11 13:16:05,808 INFO ID ALIAS MAPPER: 'subscriber_ids.json' is current, not downloaded
Traceback (most recent call last):
File "/opt/HBMonv2/monitor.py", line 996, in 
peer_ids = mk_full_id_dict(PATH, PEER_FILE, 'peer')
File "/opt/HBMonv2/monitor.py", line 130, in mk_full_id_dict
records = jload(_handle)
File "/usr/lib/python3.9/json/init.py", line 293, in load
return loads(fp.read(),
File "/usr/lib/python3.9/json/init.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Baluna24** [comment]
TG 9990Am 11.08.2023 16:37 schrieb M0VUB ***@***.***>:
TG9999 is set in ye image. What TG would you like to use? Sent from my iPhoneOn 11 Aug 2023, at 15:27, Christian ***@***.***> wrote:﻿

thank you very much that worked. I would like to change the Parrot Tg. Unfortunately, changing the hblink.cfg and rules is not enough. where do I have to change the TG?Am 11.08.2023 16:11 schrieb M0VUB ***@***.***>:



delete everything in /opt/HBMonv2/data/ all the json… it seems that when it downloaded the JSON it didn’t download it properly hence the error. Delete everything in that folder and restart by executing monitor.py. Once the dashbiard starts and is communicating properly, Cntrl C out and bring it back up using “systemctl restart hbmon”Thanks M0VUBSent from my iPhoneOn 11 Aug 2023, at 14:17, Christian ***@***.***> wrote:﻿







2023-08-11 13:16:05,807 INFO ID ALIAS MAPPER: 'peer_ids.json' is current, not downloaded







2023-08-11 13:16:05,808 INFO ID ALIAS MAPPER: 'subscriber_ids.json' is current, not downloaded







Traceback (most recent call last):







File "/opt/HBMonv2/monitor.py", line 996, in 







peer_ids = mk_full_id_dict(PATH, PEER_FILE, 'peer')







File "/opt/HBMonv2/monitor.py", line 130, in mk_full_id_dict







records = jload(_handle)







File "/usr/lib/python3.9/json/init.py", line 293, in load







return loads(fp.read(),







File "/usr/lib/python3.9/json/init.py", line 346, in loads







return _default_decoder.decode(s)







File "/usr/lib/python3.9/json/decoder.py", line 337, in decode







obj, end = self.raw_decode(s, idx=_w(s, 0).end())







File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode







raise JSONDecodeError("Expecting value", s, err.value) from None







json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ShaYmez** [comment]
Ok I’ve added 9990 along with 9999 in the permit TG’s on the parrot instance and re-built a new image. Go to the HBLink-menu, select option 4 to pull new image and restart. Then set in your rules 9990 👍, change cfg to suit. Let me know if it works.On 11 Aug 2023, at 15:44, Christian ***@***.***> wrote:﻿
TG 9990Am 11.08.2023 16:37 schrieb M0VUB ***@***.***>:

TG9999 is set in ye image. What TG would you like to use? Sent from my iPhoneOn 11 Aug 2023, at 15:27, Christian ***@***.***> wrote:﻿



thank you very much that worked. I would like to change the Parrot Tg. Unfortunately, changing the hblink.cfg and rules is not enough. where do I have to change the TG?Am 11.08.2023 16:11 schrieb M0VUB ***@***.***>:







delete everything in /opt/HBMonv2/data/ all the json… it seems that when it downloaded the JSON it didn’t download it properly hence the error. Delete everything in that folder and restart by executing monitor.py. Once the dashbiard starts and is communicating properly, Cntrl C out and bring it back up using “systemctl restart hbmon”Thanks M0VUBSent from my iPhoneOn 11 Aug 2023, at 14:17, Christian ***@***.***> wrote:﻿















2023-08-11 13:16:05,807 INFO ID ALIAS MAPPER: 'peer_ids.json' is current, not downloaded















2023-08-11 13:16:05,808 INFO ID ALIAS MAPPER: 'subscriber_ids.json' is current, not downloaded















Traceback (most recent call last):















File "/opt/HBMonv2/monitor.py", line 996, in 















peer_ids = mk_full_id_dict(PATH, PEER_FILE, 'peer')















File "/opt/HBMonv2/monitor.py", line 130, in mk_full_id_dict















records = jload(_handle)















File "/usr/lib/python3.9/json/init.py", line 293, in load















return loads(fp.read(),















File "/usr/lib/python3.9/json/init.py", line 346, in loads















return _default_decoder.decode(s)















File "/usr/lib/python3.9/json/decoder.py", line 337, in decode















obj, end = self.raw_decode(s, idx=_w(s, 0).end())















File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode















raise JSONDecodeError("Expecting value", s, err.value) from None















json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Baluna24** [comment]
Great, thank you for your work! Your Docker version is very good.Am 11.08.2023 17:56 schrieb M0VUB ***@***.***>:
Ok I’ve added 9990 along with 9999 in the permit TG’s on the parrot instance and re-built a new image. Go to the HBLink-menu, select option 4 to pull new image and restart. Then set in your rules 9990 👍, change cfg to suit. Let me know if it works.On 11 Aug 2023, at 15:44, Christian ***@***.***> wrote:﻿

TG 9990Am 11.08.2023 16:37 schrieb M0VUB ***@***.***>:



TG9999 is set in ye image. What TG would you like to use? Sent from my iPhoneOn 11 Aug 2023, at 15:27, Christian ***@***.***> wrote:﻿







thank you very much that worked. I would like to change the Parrot Tg. Unfortunately, changing the hblink.cfg and rules is not enough. where do I have to change the TG?Am 11.08.2023 16:11 schrieb M0VUB ***@***.***>:















delete everything in /opt/HBMonv2/data/ all the json… it seems that when it downloaded the JSON it didn’t download it properly hence the error. Delete everything in that folder and restart by executing monitor.py. Once the dashbiard starts and is communicating properly, Cntrl C out and bring it back up using “systemctl restart hbmon”Thanks M0VUBSent from my iPhoneOn 11 Aug 2023, at 14:17, Christian ***@***.***> wrote:﻿































2023-08-11 13:16:05,807 INFO ID ALIAS MAPPER: 'peer_ids.json' is current, not downloaded































2023-08-11 13:16:05,808 INFO ID ALIAS MAPPER: 'subscriber_ids.json' is current, not downloaded































Traceback (most recent call last):































File "/opt/HBMonv2/monitor.py", line 996, in 































peer_ids = mk_full_id_dict(PATH, PEER_FILE, 'peer')































File "/opt/HBMonv2/monitor.py", line 130, in mk_full_id_dict































records = jload(_handle)































File "/usr/lib/python3.9/json/init.py", line 293, in load































return loads(fp.read(),































File "/usr/lib/python3.9/json/init.py", line 346, in loads































return _default_decoder.decode(s)































File "/usr/lib/python3.9/json/decoder.py", line 337, in decode































obj, end = self.raw_decode(s, idx=_w(s, 0).end())































File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode































raise JSONDecodeError("Expecting value", s, err.value) from None































json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ShaYmez** [comment]
I’m glad it’s working :)Shane M0VUB On 11 Aug 2023, at 17:01, Christian ***@***.***> wrote:﻿
Great, thank you for your work! Your Docker version is very good.Am 11.08.2023 17:56 schrieb M0VUB ***@***.***>:

Ok I’ve added 9990 along with 9999 in the permit TG’s on the parrot instance and re-built a new image. Go to the HBLink-menu, select option 4 to pull new image and restart. Then set in your rules 9990 👍, change cfg to suit. Let me know if it works.On 11 Aug 2023, at 15:44, Christian ***@***.***> wrote:﻿



TG 9990Am 11.08.2023 16:37 schrieb M0VUB ***@***.***>:







TG9999 is set in ye image. What TG would you like to use? Sent from my iPhoneOn 11 Aug 2023, at 15:27, Christian ***@***.***> wrote:﻿















thank you very much that worked. I would like to change the Parrot Tg. Unfortunately, changing the hblink.cfg and rules is not enough. where do I have to change the TG?Am 11.08.2023 16:11 schrieb M0VUB ***@***.***>:































delete everything in /opt/HBMonv2/data/ all the json… it seems that when it downloaded the JSON it didn’t download it properly hence the error. Delete everything in that folder and restart by executing monitor.py. Once the dashbiard starts and is communicating properly, Cntrl C out and bring it back up using “systemctl restart hbmon”Thanks M0VUBSent from my iPhoneOn 11 Aug 2023, at 14:17, Christian ***@***.***> wrote:﻿































































2023-08-11 13:16:05,807 INFO ID ALIAS MAPPER: 'peer_ids.json' is current, not downloaded































































2023-08-11 13:16:05,808 INFO ID ALIAS MAPPER: 'subscriber_ids.json' is current, not downloaded































































Traceback (most recent call last):































































File "/opt/HBMonv2/monitor.py", line 996, in 































































peer_ids = mk_full_id_dict(PATH, PEER_FILE, 'peer')































































File "/opt/HBMonv2/monitor.py", line 130, in mk_full_id_dict































































records = jload(_handle)































































File "/usr/lib/python3.9/json/init.py", line 293, in load































































return loads(fp.read(),































































File "/usr/lib/python3.9/json/init.py", line 346, in loads































































return _default_decoder.decode(s)































































File "/usr/lib/python3.9/json/decoder.py", line 337, in decode































































obj, end = self.raw_decode(s, idx=_w(s, 0).end())































































File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode































































raise JSONDecodeError("Expecting value", s, err.value) from None































































json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Baluna24** [comment]
I have found that I cannot activate both timeslots in one TG. There still seems to be a bug?Am 11.08.2023 20:20 schrieb M0VUB ***@***.***>:
I’m glad it’s working :)Shane M0VUB On 11 Aug 2023, at 17:01, Christian ***@***.***> wrote:﻿

Great, thank you for your work! Your Docker version is very good.Am 11.08.2023 17:56 schrieb M0VUB ***@***.***>:



Ok I’ve added 9990 along with 9999 in the permit TG’s on the parrot instance and re-built a new image. Go to the HBLink-menu, select option 4 to pull new image and restart. Then set in your rules 9990 👍, change cfg to suit. Let me know if it works.On 11 Aug 2023, at 15:44, Christian ***@***.***> wrote:﻿







TG 9990Am 11.08.2023 16:37 schrieb M0VUB ***@***.***>:















TG9999 is set in ye image. What TG would you like to use? Sent from my iPhoneOn 11 Aug 2023, at 15:27, Christian ***@***.***> wrote:﻿































thank you very much that worked. I would like to change the Parrot Tg. Unfortunately, changing the hblink.cfg and rules is not enough. where do I have to change the TG?Am 11.08.2023 16:11 schrieb M0VUB ***@***.***>:































































delete everything in /opt/HBMonv2/data/ all the json… it seems that when it downloaded the JSON it didn’t download it properly hence the error. Delete everything in that folder and restart by executing monitor.py. Once the dashbiard starts and is communicating properly, Cntrl C out and bring it back up using “systemctl restart hbmon”Thanks M0VUBSent from my iPhoneOn 11 Aug 2023, at 14:17, Christian ***@***.***> wrote:﻿































































































































2023-08-11 13:16:05,807 INFO ID ALIAS MAPPER: 'peer_ids.json' is current, not downloaded































































































































2023-08-11 13:16:05,808 INFO ID ALIAS MAPPER: 'subscriber_ids.json' is current, not downloaded































































































































Traceback (most recent call last):































































































































File "/opt/HBMonv2/monitor.py", line 996, in 































































































































peer_ids = mk_full_id_dict(PATH, PEER_FILE, 'peer')































































































































File "/opt/HBMonv2/monitor.py", line 130, in mk_full_id_dict































































































































records = jload(_handle)































































































































File "/usr/lib/python3.9/json/init.py", line 293, in load































































































































return loads(fp.read(),































































































































File "/usr/lib/python3.9/json/init.py", line 346, in loads































































































































return _default_decoder.decode(s)































































































































File "/usr/lib/python3.9/json/decoder.py", line 337, in decode































































































































obj, end = self.raw_decode(s, idx=_w(s, 0).end())































































































































File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode































































































































raise JSONDecodeError("Expecting value", s, err.value) from None































































































































json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)































































































































































































































































—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>































































































































—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>































































—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>































—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>















—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>







—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by ShaYmez** [comment]
Unfortunately I don’t offer bug support on HBLink from the stable code. Bugs are handled with care as this is depreciated code. Try raising the issue on the HBLink forum. I only offer limited support on deployment and installation of HBLink. If you have an issue with bugs you may need to supply a log output and throw it in the main forum to see if someone can replicate the issue. Also check your config ```SLOTS:``` param :)ShaneM0VUBOn 13 Aug 2023, at 12:01, Christian ***@***.***> wrote:﻿
I have found that I cannot activate both timeslots in one TG. There still seems to be a bug?Am 11.08.2023 20:20 schrieb M0VUB ***@***.***>:

I’m glad it’s working :)Shane M0VUB On 11 Aug 2023, at 17:01, Christian ***@***.***> wrote:﻿



Great, thank you for your work! Your Docker version is very good.Am 11.08.2023 17:56 schrieb M0VUB ***@***.***>:







Ok I’ve added 9990 along with 9999 in the permit TG’s on the parrot instance and re-built a new image. Go to the HBLink-menu, select option 4 to pull new image and restart. Then set in your rules 9990 👍, change cfg to suit. Let me know if it works.On 11 Aug 2023, at 15:44, Christian ***@***.***> wrote:﻿















TG 9990Am 11.08.2023 16:37 schrieb M0VUB ***@***.***>:































TG9999 is set in ye image. What TG would you like to use? Sent from my iPhoneOn 11 Aug 2023, at 15:27, Christian ***@***.***> wrote:﻿































































thank you very much that worked. I would like to change the Parrot Tg. Unfortunately, changing the hblink.cfg and rules is not enough. where do I have to change the TG?Am 11.08.2023 16:11 schrieb M0VUB ***@***.***>:































































































































delete everything in /opt/HBMonv2/data/ all the json… it seems that when it downloaded the JSON it didn’t download it properly hence the error. Delete everything in that folder and restart by executing monitor.py. Once the dashbiard starts and is communicating properly, Cntrl C out and bring it back up using “systemctl restart hbmon”Thanks M0VUBSent from my iPhoneOn 11 Aug 2023, at 14:17, Christian ***@***.***> wrote:﻿































































































































































































































































2023-08-11 13:16:05,807 INFO ID ALIAS MAPPER: 'peer_ids.json' is current, not downloaded































































































































































































































































2023-08-11 13:16:05,808 INFO ID ALIAS MAPPER: 'subscriber_ids.json' is current, not downloaded































































































































































































































































Traceback (most recent call last):































































































































































































































































File "/opt/HBMonv2/monitor.py", line 996, in 































































































































































































































































peer_ids = mk_full_id_dict(PATH, PEER_FILE, 'peer')































































































































































































































































File "/opt/HBMonv2/monitor.py", line 130, in mk_full_id_dict































































































































































































































































records = jload(_handle)































































































































































































































































File "/usr/lib/python3.9/json/init.py", line 293, in load































































































































































































































































return loads(fp.read(),































































































































































































































































File "/usr/lib/python3.9/json/init.py", line 346, in loads































































































































































































































































return _default_decoder.decode(s)































































































































































































































































File "/usr/lib/python3.9/json/decoder.py", line 337, in decode































































































































































































































































obj, end = self.raw_decode(s, idx=_w(s, 0).end())































































































































































































































































File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode































































































































































































































































raise JSONDecodeError("Expecting value", s, err.value) from None































































































































































































































































json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)































































































































































































































































































































































































































































































































—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>































































































































































































































































—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>































































































































—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>































































—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>































—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>















—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>







—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
