### ISSUE TITLE
No traffic

### ISSUE THREAD

**Issue by bee-media** [ShaYmez/hblink3-docker-install#5]
Hello. Installed, everything works, but when you connect pi-star, 2 hotspot, the server sees that they have connected, but there is no traffic from them. In 2 directions. Tell me, where to look?

**Comment by ShaYmez** [comment]
The HBLink tree has now been depreciated. There is no development going to happen in the future on this project due to depreciated libraries and unsupported Python libs. Sorry the software is to outdated to keep going and I will be archiving the project.Shane M0VUBOn 23 May 2024, at 21:11, bee-media ***@***.***> wrote:﻿
Hello. Installed, everything works, but when you connect pi-star, 2 hotspot, the server sees that they have connected, but there is no traffic from them. In 2 directions. Tell me, where to look?

**Comment by ShaYmez** [comment]
I've fixed the installer and re-compiled HBMonv2. This installer currently is fully tested on debian 10 / 11. Debian 12 has been tested but some contriants with python pip. Stability is retained on debian 11. Due to a great demand in retaining this software ive updated it... But only for debian 10 / 11

**Comment by bee-media** [comment]
> I've fixed the installer and re-compiled HBMonv2. This installer currently is fully tested on debian 10 / 11. Debian 12 has been tested but some contriants with python pip. Stability is retained on debian 11. Due to a great demand in retaining this software ive updated it... But only for debian 10 / 11

Thank you very much!

**Comment by bee-media** [comment]
Installed a completely updated version. When launched it gives an error in the console.
```
ERROR: for hblink3  Cannot start service hblink3: OCI runtime create failed: container_linux.go:377: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: can't load program: operation not permitted: unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by bee-media** [comment]
> This may happen if upgrading from buster to bullseye. Make sure your kernel is up-to-date in bullseye apt install linux-image-amd64 Did you blow the old system and start a fresh ? Shane M0VUB
> […](#)
> On 18 Jun 2024, at 10:58, bee-media ***@***.***> wrote: OCI runtime create failed: container_linux.go:377: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: can't load program: operation not permitted: unknown

Hello.
Yes, I did a clean install on proxmox. Debian 11 container.
I managed to get everything running. But for some reason there is still no voice traffic.

**Comment by bee-media** [comment]
![1](https://github.com/ShaYmez/hblink3-docker-install/assets/25938240/ae852e93-61ce-4233-b77a-2d50852aa9bf)
![2](https://github.com/ShaYmez/hblink3-docker-install/assets/25938240/1eabc220-55fd-4fae-b938-7fd1875c9d30)
